### ISSUE TITLE
Visual Studio Compatibility Issues

### ISSUE THREAD

**Issue by nueverest** [paully21/SendGridWebHookExample#1]
I opened the .sln file with Visual Studios 2010 and received the following: 
![image](https://cloud.githubusercontent.com/assets/2917370/2618033/5cbb1904-bc1a-11e3-9637-4fc2b3bd1dbd.png)

This project is incompatible with the current version of Visual Studio.

Here are my Visual Studios Details
![image](https://cloud.githubusercontent.com/assets/2917370/2618045/81be41e0-bc1a-11e3-900d-69a4b1b0f8b3.png)

**Comment by paully21** [comment]
I imagine you will need VS2013…That’s what I used.

The project also uses .NET 4.5
